In [1]:
import nltk

In [2]:
from nltk.tokenize import sent_tokenize, word_tokenize

In [27]:
#write a function for tokenization
def tokenize(p):
    return word_tokenize(p)
p="""If the sentence is the essential soul to express oneself in their own way, then
the paragraph is the virtual body of it. The Text Generator is an intelligent tool
that creates random text incorporated with random thoughts. This smart tool is a 
virtual friend of yours that can talk to you in multidimensional thinking. It will provide you 
with thoughts, concepts, and ideas of different topics that will not only assist you in creating 
new knowledge but also enhance your brain function."""

tokens= tokenize(p)
print(tokens)
print(len(tokens))

['If', 'the', 'sentence', 'is', 'the', 'essential', 'soul', 'to', 'express', 'oneself', 'in', 'their', 'own', 'way', ',', 'then', 'the', 'paragraph', 'is', 'the', 'virtual', 'body', 'of', 'it', '.', 'The', 'Text', 'Generator', 'is', 'an', 'intelligent', 'tool', 'that', 'creates', 'random', 'text', 'incorporated', 'with', 'random', 'thoughts', '.', 'This', 'smart', 'tool', 'is', 'a', 'virtual', 'friend', 'of', 'yours', 'that', 'can', 'talk', 'to', 'you', 'in', 'multidimensional', 'thinking', '.', 'It', 'will', 'provide', 'you', 'with', 'thoughts', ',', 'concepts', ',', 'and', 'ideas', 'of', 'different', 'topics', 'that', 'will', 'not', 'only', 'assist', 'you', 'in', 'creating', 'new', 'knowledge', 'but', 'also', 'enhance', 'your', 'brain', 'function', '.']
90


In [21]:

from collections import Counter
def freq(tokens):
    ans= Counter(tokens)
    return ans
print(Counter(tokens))

Counter({'the': 4, 'is': 4, '.': 4, 'in': 3, ',': 3, 'of': 3, 'that': 3, 'you': 3, 'to': 2, 'virtual': 2, 'tool': 2, 'random': 2, 'with': 2, 'thoughts': 2, 'will': 2, 'If': 1, 'sentence': 1, 'essential': 1, 'soul': 1, 'express': 1, 'oneself': 1, 'their': 1, 'own': 1, 'way': 1, 'then': 1, 'paragraph': 1, 'body': 1, 'it': 1, 'The': 1, 'Text': 1, 'Generator': 1, 'an': 1, 'intelligent': 1, 'creates': 1, 'text': 1, 'incorporated': 1, 'This': 1, 'smart': 1, 'a': 1, 'friend': 1, 'yours': 1, 'can': 1, 'talk': 1, 'multidimensional': 1, 'thinking': 1, 'It': 1, 'provide': 1, 'concepts': 1, 'and': 1, 'ideas': 1, 'different': 1, 'topics': 1, 'not': 1, 'only': 1, 'assist': 1, 'creating': 1, 'new': 1, 'knowledge': 1, 'but': 1, 'also': 1, 'enhance': 1, 'your': 1, 'brain': 1, 'function': 1})


In [23]:

extract=sorted(set(tokens))
print(extract)
print(len(extract))

[',', '.', 'Generator', 'If', 'It', 'Text', 'The', 'This', 'a', 'also', 'an', 'and', 'assist', 'body', 'brain', 'but', 'can', 'concepts', 'creates', 'creating', 'different', 'enhance', 'essential', 'express', 'friend', 'function', 'ideas', 'in', 'incorporated', 'intelligent', 'is', 'it', 'knowledge', 'multidimensional', 'new', 'not', 'of', 'oneself', 'only', 'own', 'paragraph', 'provide', 'random', 'sentence', 'smart', 'soul', 'talk', 'text', 'that', 'the', 'their', 'then', 'thinking', 'thoughts', 'to', 'tool', 'topics', 'virtual', 'way', 'will', 'with', 'you', 'your', 'yours']
64


In [24]:
pip install numpy


     -------------------------------------- 15.6/15.6 MB 748.3 kB/s eta 0:00:00


You should consider upgrading via the 'c:\Python310\python.exe -m pip install --upgrade pip' command.


In [1]:
import numpy
import re

def word_extraction(sentence):
    ignore = ["a","the","is"]
    words = re.sub("[^\w]"," ",sentence).split()
    cleaned_text = [w.lower() for w in words if w not in ignore]
    return cleaned_text
def tokenize(allsentences):
    vocab = []
    for sentence in allsentences:
        w = word_extraction(sentence)
        vocab.extend(w)
    return sorted(list(set(vocab)))
def generate_bow(allsentences):
    vocab = tokenize(allsentences)
    print("word_text for document:9\n{0}\n".format(vocab))
    for sentence in allsentences:
        words = word_extraction(sentence)
        bag_vector = numpy.zeros(len(vocab))
        for w in words:
            for i, word in enumerate(vocab):
                if word == w:
                    bag_vector[i] += 1
        print("Sentence:\n{0}\nBoW Vector:\n{1}\n".format(sentence,bag_vector))
allsentences = ["Joe waited for the train", "the train was late", "May and Samantha took the bus"]
generate_bow(allsentences)


word_text for document:9
['and', 'bus', 'for', 'joe', 'late', 'may', 'samantha', 'took', 'train', 'waited', 'was']

Sentence:
Joe waited for the train
BoW Vector:
[0. 0. 1. 1. 0. 0. 0. 0. 1. 1. 0.]

Sentence:
the train was late
BoW Vector:
[0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 1.]

Sentence:
May and Samantha took the bus
BoW Vector:
[1. 1. 0. 0. 0. 1. 1. 1. 0. 0. 0.]



##### How to prepare your data through bag of words for regression

In [5]:
# how to prepare data (vector) through bow for regression 

import numpy as np
import re

def tokenize(corpus):
    words = []
    for sentence in corpus:
        w = word_extraction(sentence)
        words.extend(w)
        
    words = sorted(list(set(words)))
    return words

def word_extraction(corpus):
    ignore = ["a", "the", "is"]
    words = re.sub(r'[^\w]', ' ', corpus).split()
    cleaned_text = [w.lower() for w in words if w.lower() not in ignore]
    return cleaned_text

def generate_bow(allSentences, vocab):
    data = []
    for corpus in allSentences:
        words = word_extraction(corpus)
        bag_vector = np.zeros(len(vocab))
        for w in words:
            for i, word in enumerate(vocab):
                if word == w:
                    bag_vector[i] += 1
        data.append(bag_vector)
    return np.array(data)

# Example data
allSentences = ["Joe waited for the train", "the train was late", "May and Samantha took the bus"]

vocab = tokenize(allSentences)
bow_data = generate_bow(allSentences, vocab)
print(bow_data)

[[0. 0. 1. 1. 0. 0. 0. 0. 1. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 1.]
 [1. 1. 0. 0. 0. 1. 1. 1. 0. 0. 0.]]
